/*
-----------------File generated by testsGen.py-----------------
*/
#include <gtest/gtest.h>
#include <string>
#include <sstream>
#include "parser.h"

std::string fileToString(std::string name) {
    std::ifstream fout(name);
    std::stringstream sout;
    sout << fout.rdbuf();
    return sout.str();
}

TEST(ParserExprTests, test000) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test000.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test000.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test000.in");
}

TEST(ParserExprTests, test001) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test001.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test001.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test001.in");
}

TEST(ParserExprTests, test002) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test002.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test002.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test002.in");
}

TEST(ParserExprTests, test003) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test003.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test003.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test003.in");
}

TEST(ParserExprTests, test004) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test004.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test004.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test004.in");
}

TEST(ParserExprTests, test005) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test005.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test005.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test005.in");
}

TEST(ParserExprTests, test006) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test006.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test006.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test006.in");
}

TEST(ParserExprTests, test007) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test007.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test007.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test007.in");
}

TEST(ParserExprTests, test008) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test008.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test008.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test008.in");
}

TEST(ParserExprTests, test009) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test009.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test009.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test009.in");
}

TEST(ParserExprTests, test010) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test010.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test010.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test010.in");
}

TEST(ParserExprTests, test011) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test011.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test011.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test011.in");
}

TEST(ParserExprTests, test012) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test012.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test012.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test012.in");
}

TEST(ParserExprTests, test013) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test013.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test013.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test013.in");
}

TEST(ParserExprTests, test014) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test014.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test014.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test014.in");
}

TEST(ParserExprTests, test015) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test015.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test015.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test015.in");
}

TEST(ParserExprTests, test016) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test016.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test016.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test016.in");
}

TEST(ParserExprTests, test017) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test017.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test017.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test017.in");
}

TEST(ParserExprTests, test018) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test018.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test018.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test018.in");
}

TEST(ParserExprTests, test019) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test019.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test019.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test019.in");
}

TEST(ParserExprTests, test020) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test020.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test020.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test020.in");
}

TEST(ParserExprTests, test021) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test021.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test021.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test021.in");
}

TEST(ParserExprTests, test022) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test022.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test022.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test022.in");
}

TEST(ParserExprTests, test023) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test023.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test023.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test023.in");
}

TEST(ParserExprTests, test024) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test024.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test024.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test024.in");
}

TEST(ParserExprTests, test025) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test025.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test025.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test025.in");
}

TEST(ParserExprTests, test026) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test026.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test026.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test026.in");
}

TEST(ParserExprTests, test027) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test027.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test027.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test027.in");
}

TEST(ParserExprTests, test028) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test028.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test028.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test028.in");
}

TEST(ParserExprTests, test029) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test029.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test029.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test029.in");
}

TEST(ParserExprTests, test030) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test030.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test030.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test030.in");
}

TEST(ParserExprTests, test031) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test031.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test031.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test031.in");
}

TEST(ParserExprTests, test032) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test032.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test032.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test032.in");
}

TEST(ParserExprTests, test033) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test033.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test033.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test033.in");
}

TEST(ParserExprTests, test034) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test034.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test034.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test034.in");
}

TEST(ParserExprTests, test035) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test035.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test035.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test035.in");
}

TEST(ParserExprTests, test036) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test036.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test036.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test036.in");
}

TEST(ParserExprTests, test037) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test037.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test037.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test037.in");
}

TEST(ParserExprTests, test038) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test038.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test038.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test038.in");
}

TEST(ParserExprTests, test039) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test039.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test039.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test039.in");
}

TEST(ParserExprTests, test040) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test040.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test040.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test040.in");
}

TEST(ParserExprTests, test041) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test041.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test041.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test041.in");
}

TEST(ParserExprTests, test042) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test042.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test042.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test042.in");
}

TEST(ParserExprTests, test043) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test043.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test043.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test043.in");
}

TEST(ParserExprTests, test044) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test044.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test044.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test044.in");
}

TEST(ParserExprTests, test045) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test045.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test045.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test045.in");
}

TEST(ParserExprTests, test046) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test046.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test046.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test046.in");
}

TEST(ParserExprTests, test047) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test047.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test047.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test047.in");
}

TEST(ParserExprTests, test048) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test048.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test048.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test048.in");
}

TEST(ParserExprTests, test049) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test049.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test049.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test049.in");
}

TEST(ParserExprTests, test050) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test050.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test050.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test050.in");
}

TEST(ParserExprTests, test051) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test051.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test051.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test051.in");
}

TEST(ParserExprTests, test052) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test052.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test052.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test052.in");
}

TEST(ParserExprTests, test053) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test053.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test053.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test053.in");
}

TEST(ParserExprTests, test054) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test054.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test054.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test054.in");
}

TEST(ParserExprTests, test055) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test055.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test055.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test055.in");
}

TEST(ParserExprTests, test056) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test056.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test056.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test056.in");
}

TEST(ParserExprTests, test057) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test057.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test057.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test057.in");
}

TEST(ParserExprTests, test058) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test058.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test058.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test058.in");
}

TEST(ParserExprTests, test059) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test059.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test059.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test059.in");
}

TEST(ParserExprTests, test060) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test060.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test060.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test060.in");
}

TEST(ParserExprTests, test061) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test061.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test061.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test061.in");
}

TEST(ParserExprTests, test062) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test062.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test062.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test062.in");
}

TEST(ParserExprTests, test063) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test063.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test063.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test063.in");
}

TEST(ParserExprTests, test064) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test064.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test064.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test064.in");
}

TEST(ParserExprTests, test065) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test065.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test065.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test065.in");
}

TEST(ParserExprTests, test066) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test066.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test066.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test066.in");
}

TEST(ParserExprTests, test067) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test067.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test067.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test067.in");
}

TEST(ParserExprTests, test068) {
    EXPECT_EQ(fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test068.out"), fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/MyOut/test068.out")) << "Input: " << std::endl << fileToString("/home/nikita/Documents/C++/Compiler/Tests/GeneratorTests/test068.in");
}

