/*
-----------------File generated by testsGen.py-----------------
*/
#include <gtest/gtest.h>
#include <string>
#include <sstream>
#include "parser.h"

std::string fileToString(std::string name) {
    std::ifstream fout(name);
    std::stringstream sout;
    sout << fout.rdbuf();
    return sout.str();
}

TEST(ParserExprTests, test000) {
    Parser parser("test000.in");
    EXPECT_EQ(fileToString("test000.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test000.in");
}

TEST(ParserExprTests, test001) {
    Parser parser("test001.in");
    EXPECT_EQ(fileToString("test001.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test001.in");
}

TEST(ParserExprTests, test002) {
    Parser parser("test002.in");
    EXPECT_EQ(fileToString("test002.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test002.in");
}

TEST(ParserExprTests, test003) {
    Parser parser("test003.in");
    EXPECT_EQ(fileToString("test003.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test003.in");
}

TEST(ParserExprTests, test004) {
    Parser parser("test004.in");
    EXPECT_EQ(fileToString("test004.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test004.in");
}

TEST(ParserExprTests, test005) {
    Parser parser("test005.in");
    EXPECT_EQ(fileToString("test005.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test005.in");
}

TEST(ParserExprTests, test006) {
    Parser parser("test006.in");
    EXPECT_EQ(fileToString("test006.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test006.in");
}

TEST(ParserExprTests, test007) {
    Parser parser("test007.in");
    EXPECT_EQ(fileToString("test007.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test007.in");
}

TEST(ParserExprTests, test008) {
    Parser parser("test008.in");
    EXPECT_EQ(fileToString("test008.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test008.in");
}

TEST(ParserExprTests, test009) {
    Parser parser("test009.in");
    EXPECT_EQ(fileToString("test009.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test009.in");
}

TEST(ParserExprTests, test010) {
    Parser parser("test010.in");
    EXPECT_EQ(fileToString("test010.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test010.in");
}

TEST(ParserExprTests, test011) {
    Parser parser("test011.in");
    EXPECT_EQ(fileToString("test011.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test011.in");
}

TEST(ParserExprTests, test012) {
    Parser parser("test012.in");
    EXPECT_EQ(fileToString("test012.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test012.in");
}

TEST(ParserExprTests, test013) {
    Parser parser("test013.in");
    EXPECT_EQ(fileToString("test013.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test013.in");
}

TEST(ParserExprTests, test014) {
    Parser parser("test014.in");
    EXPECT_EQ(fileToString("test014.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test014.in");
}

TEST(ParserExprTests, test015) {
    Parser parser("test015.in");
    EXPECT_EQ(fileToString("test015.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test015.in");
}

TEST(ParserExprTests, test016) {
    Parser parser("test016.in");
    EXPECT_EQ(fileToString("test016.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test016.in");
}

TEST(ParserExprTests, test017) {
    Parser parser("test017.in");
    EXPECT_EQ(fileToString("test017.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test017.in");
}

TEST(ParserExprTests, test018) {
    Parser parser("test018.in");
    EXPECT_EQ(fileToString("test018.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test018.in");
}

TEST(ParserExprTests, test019) {
    Parser parser("test019.in");
    EXPECT_EQ(fileToString("test019.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test019.in");
}

TEST(ParserExprTests, test020) {
    Parser parser("test020.in");
    EXPECT_EQ(fileToString("test020.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test020.in");
}

TEST(ParserExprTests, test021) {
    Parser parser("test021.in");
    EXPECT_EQ(fileToString("test021.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test021.in");
}

TEST(ParserExprTests, test022) {
    Parser parser("test022.in");
    EXPECT_EQ(fileToString("test022.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test022.in");
}

TEST(ParserExprTests, test023) {
    Parser parser("test023.in");
    EXPECT_EQ(fileToString("test023.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test023.in");
}

TEST(ParserExprTests, test024) {
    Parser parser("test024.in");
    EXPECT_EQ(fileToString("test024.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test024.in");
}

TEST(ParserExprTests, test025) {
    Parser parser("test025.in");
    EXPECT_EQ(fileToString("test025.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test025.in");
}

TEST(ParserExprTests, test026) {
    Parser parser("test026.in");
    EXPECT_EQ(fileToString("test026.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test026.in");
}

TEST(ParserExprTests, test027) {
    Parser parser("test027.in");
    EXPECT_EQ(fileToString("test027.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test027.in");
}

TEST(ParserExprTests, test028) {
    Parser parser("test028.in");
    EXPECT_EQ(fileToString("test028.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test028.in");
}

TEST(ParserExprTests, test029) {
    Parser parser("test029.in");
    EXPECT_EQ(fileToString("test029.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test029.in");
}

TEST(ParserExprTests, test030) {
    Parser parser("test030.in");
    EXPECT_EQ(fileToString("test030.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test030.in");
}

TEST(ParserExprTests, test031) {
    Parser parser("test031.in");
    EXPECT_EQ(fileToString("test031.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test031.in");
}

TEST(ParserExprTests, test032) {
    Parser parser("test032.in");
    EXPECT_EQ(fileToString("test032.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test032.in");
}

TEST(ParserExprTests, test033) {
    Parser parser("test033.in");
    EXPECT_EQ(fileToString("test033.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test033.in");
}

TEST(ParserExprTests, test034) {
    Parser parser("test034.in");
    EXPECT_EQ(fileToString("test034.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test034.in");
}

TEST(ParserExprTests, test035) {
    Parser parser("test035.in");
    EXPECT_EQ(fileToString("test035.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test035.in");
}

TEST(ParserExprTests, test036) {
    Parser parser("test036.in");
    EXPECT_EQ(fileToString("test036.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test036.in");
}

TEST(ParserExprTests, test037) {
    Parser parser("test037.in");
    EXPECT_EQ(fileToString("test037.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test037.in");
}

TEST(ParserExprTests, test038) {
    Parser parser("test038.in");
    EXPECT_EQ(fileToString("test038.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test038.in");
}

TEST(ParserExprTests, test039) {
    Parser parser("test039.in");
    EXPECT_EQ(fileToString("test039.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test039.in");
}

TEST(ParserExprTests, test040) {
    Parser parser("test040.in");
    EXPECT_EQ(fileToString("test040.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test040.in");
}

TEST(ParserExprTests, test041) {
    Parser parser("test041.in");
    EXPECT_EQ(fileToString("test041.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test041.in");
}

TEST(ParserExprTests, test042) {
    Parser parser("test042.in");
    EXPECT_EQ(fileToString("test042.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test042.in");
}

TEST(ParserExprTests, test043) {
    Parser parser("test043.in");
    EXPECT_EQ(fileToString("test043.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test043.in");
}

TEST(ParserExprTests, test044) {
    Parser parser("test044.in");
    EXPECT_EQ(fileToString("test044.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test044.in");
}

TEST(ParserExprTests, test045) {
    Parser parser("test045.in");
    EXPECT_EQ(fileToString("test045.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test045.in");
}

TEST(ParserExprTests, test046) {
    Parser parser("test046.in");
    EXPECT_EQ(fileToString("test046.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test046.in");
}

TEST(ParserExprTests, test047) {
    Parser parser("test047.in");
    EXPECT_EQ(fileToString("test047.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test047.in");
}

TEST(ParserExprTests, test048) {
    Parser parser("test048.in");
    EXPECT_EQ(fileToString("test048.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test048.in");
}

TEST(ParserExprTests, test049) {
    Parser parser("test049.in");
    EXPECT_EQ(fileToString("test049.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test049.in");
}

TEST(ParserExprTests, test050) {
    Parser parser("test050.in");
    EXPECT_EQ(fileToString("test050.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test050.in");
}

TEST(ParserExprTests, test051) {
    Parser parser("test051.in");
    EXPECT_EQ(fileToString("test051.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test051.in");
}

TEST(ParserExprTests, test052) {
    Parser parser("test052.in");
    EXPECT_EQ(fileToString("test052.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test052.in");
}

TEST(ParserExprTests, test053) {
    Parser parser("test053.in");
    EXPECT_EQ(fileToString("test053.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test053.in");
}

TEST(ParserExprTests, test054) {
    Parser parser("test054.in");
    EXPECT_EQ(fileToString("test054.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test054.in");
}

TEST(ParserExprTests, test055) {
    Parser parser("test055.in");
    EXPECT_EQ(fileToString("test055.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test055.in");
}

TEST(ParserExprTests, test056) {
    Parser parser("test056.in");
    EXPECT_EQ(fileToString("test056.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test056.in");
}

TEST(ParserExprTests, test057) {
    Parser parser("test057.in");
    EXPECT_EQ(fileToString("test057.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test057.in");
}

TEST(ParserExprTests, test058) {
    Parser parser("test058.in");
    EXPECT_EQ(fileToString("test058.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test058.in");
}

TEST(ParserExprTests, test059) {
    Parser parser("test059.in");
    EXPECT_EQ(fileToString("test059.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test059.in");
}

TEST(ParserExprTests, test060) {
    Parser parser("test060.in");
    EXPECT_EQ(fileToString("test060.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test060.in");
}

TEST(ParserExprTests, test061) {
    Parser parser("test061.in");
    EXPECT_EQ(fileToString("test061.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test061.in");
}

TEST(ParserExprTests, test062) {
    Parser parser("test062.in");
    EXPECT_EQ(fileToString("test062.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test062.in");
}

TEST(ParserExprTests, test063) {
    Parser parser("test063.in");
    EXPECT_EQ(fileToString("test063.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test063.in");
}

TEST(ParserExprTests, test064) {
    Parser parser("test064.in");
    EXPECT_EQ(fileToString("test064.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test064.in");
}

TEST(ParserExprTests, test065) {
    Parser parser("test065.in");
    EXPECT_EQ(fileToString("test065.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test065.in");
}

TEST(ParserExprTests, test066) {
    Parser parser("test066.in");
    EXPECT_EQ(fileToString("test066.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test066.in");
}

TEST(ParserExprTests, test067) {
    Parser parser("test067.in");
    EXPECT_EQ(fileToString("test067.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test067.in");
}

TEST(ParserExprTests, test068) {
    Parser parser("test068.in");
    EXPECT_EQ(fileToString("test068.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test068.in");
}

TEST(ParserExprTests, test069) {
    Parser parser("test069.in");
    EXPECT_EQ(fileToString("test069.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test069.in");
}

TEST(ParserExprTests, test070) {
    Parser parser("test070.in");
    EXPECT_EQ(fileToString("test070.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test070.in");
}

TEST(ParserExprTests, test071) {
    Parser parser("test071.in");
    EXPECT_EQ(fileToString("test071.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test071.in");
}

TEST(ParserExprTests, test072) {
    Parser parser("test072.in");
    EXPECT_EQ(fileToString("test072.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test072.in");
}

TEST(ParserExprTests, test073) {
    Parser parser("test073.in");
    EXPECT_EQ(fileToString("test073.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test073.in");
}

TEST(ParserExprTests, test074) {
    Parser parser("test074.in");
    EXPECT_EQ(fileToString("test074.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test074.in");
}

TEST(ParserExprTests, test075) {
    Parser parser("test075.in");
    EXPECT_EQ(fileToString("test075.out"), parser.getDeclTestString()) << "Input: " << std::endl << fileToString("test075.in");
}

